## 2021/2022 Premier League Analysis

Perform a simple analysis, using SQL, of 2021/2022 season of the Premier League.

In [17]:
import sqlalchemy as sa

engine = sa.create_engine('postgresql://postgres:@localhost:5432/football_stats')

In [18]:
# Load the SQL extension
%load_ext sql
# Set up connection
%sql $engine.url

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: postgres@football_stats'

In [19]:
%%sql 

SELECT * 
FROM pl_clubs

 * postgresql://postgres:***@localhost:5432/football_stats
20 rows affected.

[('Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 ('Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 ('Brentford', 'London (Brentford)', 'Brentford Community Stadium', 17250, 'Thomas Frank', 'Pontus Jansson', 'Umbro', 'Hollywoodbets', 'Safetyculture'),
 ('Brighton & Hove Albion', 'Falmer', 'Falmer Stadium', 31800, 'Graham Potter', 'Lewis Dunk', 'Nike', 'American Express', 'SnickersUK.com'),
 ('Burnley', 'Burnley', 'Turf Moor', 21944, 'Mike Jackson Connor King Ben Mee (joint-caretakers)', 'Ben Mee', 'Umbro', 'Spreadex Sports', 'AstroPay'),
 ('Chelsea', 'London (Fulham)', 'Stamford Bridge', 40834, 'Thomas Tuchel', 'César Azpilicueta', 'Nike', 'Threec ', 'Hyundaic '),
 ('Crystal Palace', 'London (Selhurst)', 'Selhurst Park', 25486, 'Patrick Vieira', 'Luka Milivojević', 'Puma', 'W88', 'Facebank'),
 ('Everton', 'Liverpool (Walton)', 'Goodison Park', 39414, 'Frank Lampard', 'Séamus Coleman', 'Hummel', 'Cazoo', 'None'),
 ('Leeds United', 'Leeds', 'Elland Road', 37792, 'Jesse Marsch', 'Liam Cooper', 'Adidas', 'SBOTOP', 'BOXT'),
 ('Leicester City', 'Leicester', 'King Power Stadium', 32312, 'Brendan Rodgers', 'Kasper Schmeichel', 'Adidas', 'FBS', 'Bia Saigon'),
 ('Liverpool', 'Liverpool (Anfield)', 'Anfield', 53394, 'Jürgen Klopp', 'Jordan Henderson', 'Nike', 'Standard Chartered', 'Expedia'),
 ('Manchester City', 'Manchester (Bradford)', 'Etihad Stadium', 53400, 'Pep Guardiola', 'Fernandinho', 'Puma', 'Etihad Airways', 'Nexen Tire'),
 ('Manchester United', 'Manchester (Old Trafford)', 'Old Trafford', 74140, 'Ralf Rangnick (interim)', 'Harry Maguire', 'Adidas', 'TeamViewer', 'Kohler'),
 ('Newcastle United', 'Newcastle upon Tyne', "St James' Park", 52305, 'Eddie Howe', 'Jamaal Lascelles', 'Castore', 'FUN88', 'Kayak'),
 ('Norwich City', 'Norwich', 'Carrow Road', 27244, 'Dean Smith', 'Grant Hanley', 'Joma', 'Lotus Cars', 'JD Sports'),
 ('Southampton', 'Southampton', "St Mary's Stadium", 32384, 'Ralph Hasenhüttl', 'James Ward-Prowse', 'Hummel', 'Sportsbet.io', 'Virgin Media'),
 ('Tottenham Hotspur', 'London (Tottenham)', 'Tottenham Hotspur Stadium', 62850, 'Antonio Conte', 'Hugo Lloris', 'Nike', 'AIA', 'Cinch'),
 ('Watford', 'Watford', 'Vicarage Road', 22200, 'Roy Hodgson', 'TBDb', 'Kelme', 'Stake.com', 'Dogecoin'),
 ('West Ham United', 'London (Stratford)', 'London Stadium', 60000, 'David Moyes', 'Mark Noble', 'Umbro', 'Betway', 'Scope Markets'),
 ('Wolverhampton Wanderers', 'Wolverhampton', 'Molineux Stadium', 32050, 'Bruno Lage', 'Conor Coady', 'Castore', 'ManBetX', 'Bitci.com')]

In [20]:
%%sql 

SELECT *
FROM pl_players
LIMIT 20

 * postgresql://postgres:***@localhost:5432/football_stats
20 rows affected.

[(1, 'Bukayo Saka', 'Arsenal', 'eng\xa0ENG', 'FW,MF', 19, 38, 36, '2,978', Decimal('33.10'), 11, 7),
 (2, 'Gabriel Dos Santos', 'Arsenal', 'br\xa0BRA', 'DF', 23, 35, 35, '3,063', Decimal('34.00'), 5, 0),
 (3, 'Aaron Ramsdale', 'Arsenal', 'eng\xa0ENG', 'GK', 23, 34, 34, '3,060', Decimal('34.00'), 0, 0),
 (4, 'Ben White', 'Arsenal', 'eng\xa0ENG', 'DF', 23, 32, 32, '2,880', Decimal('32.00'), 0, 0),
 (5, 'Martin Ødegaard', 'Arsenal', 'no\xa0NOR', 'MF', 22, 36, 32, '2,785', Decimal('30.90'), 7, 4),
 (6, 'Granit Xhaka', 'Arsenal', 'ch\xa0SUI', 'MF,DF', 28, 27, 27, '2,327', Decimal('25.90'), 1, 2),
 (7, 'Thomas Partey', 'Arsenal', 'gh\xa0GHA', 'MF', 28, 24, 23, '2,028', Decimal('22.50'), 2, 1),
 (8, 'Kieran Tierney', 'Arsenal', 'sct\xa0SCO', 'DF', 24, 22, 22, '1,915', Decimal('21.30'), 1, 3),
 (9, 'Emile Smith Rowe', 'Arsenal', 'eng\xa0ENG', 'MF,FW', 21, 33, 21, '1,921', Decimal('21.30'), 10, 2),
 (10, 'Martinelli', 'Arsenal', 'br\xa0BRA', 'FW,MF', 20, 29, 21, '1,860', Decimal('20.70'), 6, 6),
 (11, 'Alexandre Lacazette', 'Arsenal', 'fr\xa0FRA', 'FW,MF', 30, 30, 20, '1,782', Decimal('19.80'), 4, 7),
 (12, 'Takehiro Tomiyasu', 'Arsenal', 'jp\xa0JPN', 'DF', 22, 21, 20, '1,679', Decimal('18.70'), 0, 1),
 (13, 'Cédric Soares', 'Arsenal', 'pt\xa0POR', 'DF', 29, 21, 16, '1,486', Decimal('16.50'), 1, 1),
 (14, 'Nuno Tavares', 'Arsenal', 'pt\xa0POR', 'DF', 21, 22, 13, '1,176', Decimal('13.10'), 1, 1),
 (15, 'Albert Sambi Lokonga', 'Arsenal', 'be\xa0BEL', 'MF', 21, 19, 12, '1,134', Decimal('12.60'), 0, 0),
 (16, 'Pierre-Emerick Aubameyang', 'Arsenal', 'ga\xa0GAB', 'FW', 32, 14, 12, '1,037', Decimal('11.50'), 4, 1),
 (17, 'Rob Holding', 'Arsenal', 'eng\xa0ENG', 'DF', 25, 15, 9, '845', Decimal('9.40'), 1, 0),
 (18, 'Eddie Nketiah', 'Arsenal', 'eng\xa0ENG', 'FW', 22, 21, 8, '835', Decimal('9.30'), 5, 1),
 (19, 'Mohamed Elneny', 'Arsenal', 'eg\xa0EGY', 'MF', 29, 14, 8, '806', Decimal('9.00'), 0, 2),
 (20, 'Nicolas Pépé', 'Arsenal', 'ci\xa0CIV', 'FW,MF', 26, 20, 5, '696', Decimal('7.70'), 1, 2)]

Find out the top 10 goal scorers and assisters:

In [21]:
%%sql
SELECT player, team, goals
FROM pl_players
WHERE goals IS NOT NULL
ORDER BY goals DESC
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/football_stats
10 rows affected.

[('Mohamed Salah', 'Liverpool', 23),
 ('Son Heung-min', 'Tottenham Hotspur', 23),
 ('Cristiano Ronaldo', 'Manchester United', 18),
 ('Harry Kane', 'Tottenham Hotspur', 17),
 ('Sadio Mané', 'Liverpool', 16),
 ('Kevin De Bruyne', 'Manchester City', 15),
 ('Jamie Vardy', 'Leicester City', 15),
 ('Diogo Jota', 'Liverpool', 15),
 ('Wilfried Zaha', 'Crystal Palace', 14),
 ('Raheem Sterling', 'Manchester City', 13)]

In [22]:
%%sql
SELECT player, team, assists
FROM pl_players
WHERE assists IS NOT NULL
ORDER BY assists DESC
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/football_stats
10 rows affected.

[('Mohamed Salah', 'Liverpool', 13),
 ('Trent Alexander-Arnold', 'Liverpool', 12),
 ('Jarrod Bowen', 'West Ham United', 10),
 ('Harvey Barnes', 'Leicester City', 10),
 ('Andrew Robertson', 'Liverpool', 10),
 ('Mason Mount', 'Chelsea', 10),
 ('Reece James', 'Chelsea', 9),
 ('Paul Pogba', 'Manchester United', 9),
 ('Harry Kane', 'Tottenham Hotspur', 9),
 ('James Maddison', 'Leicester City', 8)]

In [29]:
%%sql
SELECT team, SUM(goals) AS total_goals
FROM pl_players 
GROUP BY team
ORDER BY total_goals DESC;

 * postgresql://postgres:***@localhost:5432/football_stats
20 rows affected.

[('Manchester City', 96),
 ('Liverpool', 94),
 ('Chelsea', 75),
 ('Tottenham Hotspur', 63),
 ('Leicester City', 62),
 ('Arsenal', 60),
 ('West Ham United', 58),
 ('Manchester United', 56),
 ('Crystal Palace', 50),
 ('Aston Villa', 50),
 ('Brentford', 46),
 ('Leeds United', 42),
 ('Everton', 42),
 ('Newcastle United', 41),
 ('Southampton', 41),
 ('Brighton & Hove Albion', 40),
 ('Wolverhampton Wanderers', 35),
 ('Watford', 33),
 ('Burnley', 32),
 ('Norwich City', 21)]

In [33]:
%%sql
SELECT player, team, goals
FROM pl_players as pl
WHERE goals = (
    SELECT MAX(goals)
    FROM pl_players
    WHERE team = pl.team
)

 * postgresql://postgres:***@localhost:5432/football_stats
21 rows affected.

[('Bukayo Saka', 'Arsenal', 11),
 ('Ollie Watkins', 'Aston Villa', 11),
 ('Ivan Toney', 'Brentford', 12),
 ('Leandro Trossard', 'Brighton & Hove Albion', 8),
 ('Neal Maupay', 'Brighton & Hove Albion', 8),
 ('Maxwel Cornet', 'Burnley', 9),
 ('Mason Mount', 'Chelsea', 11),
 ('Wilfried Zaha', 'Crystal Palace', 14),
 ('Richarlison', 'Everton', 10),
 ('Raphael Dias Belloli', 'Leeds United', 11),
 ('Jamie Vardy', 'Leicester City', 15),
 ('Mohamed Salah', 'Liverpool', 23),
 ('Kevin De Bruyne', 'Manchester City', 15),
 ('Cristiano Ronaldo', 'Manchester United', 18),
 ('Callum Wilson', 'Newcastle United', 8),
 ('Teemu Pukki', 'Norwich City', 11),
 ('James Ward-Prowse', 'Southampton', 10),
 ('Son Heung-min', 'Tottenham Hotspur', 23),
 ('Emmanuel Dennis', 'Watford', 10),
 ('Jarrod Bowen', 'West Ham United', 12),
 ('Raúl Jiménez', 'Wolverhampton Wanderers', 6)]

In [39]:
%%sql
SELECT *
FROM pl_players pl INNER JOIN pl_clubs cl ON pl.team = cl.team
LIMIT 50;

 * postgresql://postgres:***@localhost:5432/football_stats
50 rows affected.

[(1, 'Bukayo Saka', 'Arsenal', 'eng\xa0ENG', 'FW,MF', 19, 38, 36, '2,978', Decimal('33.10'), 11, 7, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (2, 'Gabriel Dos Santos', 'Arsenal', 'br\xa0BRA', 'DF', 23, 35, 35, '3,063', Decimal('34.00'), 5, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (3, 'Aaron Ramsdale', 'Arsenal', 'eng\xa0ENG', 'GK', 23, 34, 34, '3,060', Decimal('34.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (4, 'Ben White', 'Arsenal', 'eng\xa0ENG', 'DF', 23, 32, 32, '2,880', Decimal('32.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (5, 'Martin Ødegaard', 'Arsenal', 'no\xa0NOR', 'MF', 22, 36, 32, '2,785', Decimal('30.90'), 7, 4, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (6, 'Granit Xhaka', 'Arsenal', 'ch\xa0SUI', 'MF,DF', 28, 27, 27, '2,327', Decimal('25.90'), 1, 2, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (7, 'Thomas Partey', 'Arsenal', 'gh\xa0GHA', 'MF', 28, 24, 23, '2,028', Decimal('22.50'), 2, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (8, 'Kieran Tierney', 'Arsenal', 'sct\xa0SCO', 'DF', 24, 22, 22, '1,915', Decimal('21.30'), 1, 3, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (9, 'Emile Smith Rowe', 'Arsenal', 'eng\xa0ENG', 'MF,FW', 21, 33, 21, '1,921', Decimal('21.30'), 10, 2, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (10, 'Martinelli', 'Arsenal', 'br\xa0BRA', 'FW,MF', 20, 29, 21, '1,860', Decimal('20.70'), 6, 6, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (11, 'Alexandre Lacazette', 'Arsenal', 'fr\xa0FRA', 'FW,MF', 30, 30, 20, '1,782', Decimal('19.80'), 4, 7, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (12, 'Takehiro Tomiyasu', 'Arsenal', 'jp\xa0JPN', 'DF', 22, 21, 20, '1,679', Decimal('18.70'), 0, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (13, 'Cédric Soares', 'Arsenal', 'pt\xa0POR', 'DF', 29, 21, 16, '1,486', Decimal('16.50'), 1, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (14, 'Nuno Tavares', 'Arsenal', 'pt\xa0POR', 'DF', 21, 22, 13, '1,176', Decimal('13.10'), 1, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (15, 'Albert Sambi Lokonga', 'Arsenal', 'be\xa0BEL', 'MF', 21, 19, 12, '1,134', Decimal('12.60'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (16, 'Pierre-Emerick Aubameyang', 'Arsenal', 'ga\xa0GAB', 'FW', 32, 14, 12, '1,037', Decimal('11.50'), 4, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (17, 'Rob Holding', 'Arsenal', 'eng\xa0ENG', 'DF', 25, 15, 9, '845', Decimal('9.40'), 1, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (18, 'Eddie Nketiah', 'Arsenal', 'eng\xa0ENG', 'FW', 22, 21, 8, '835', Decimal('9.30'), 5, 1, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (19, 'Mohamed Elneny', 'Arsenal', 'eg\xa0EGY', 'MF', 29, 14, 8, '806', Decimal('9.00'), 0, 2, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (20, 'Nicolas Pépé', 'Arsenal', 'ci\xa0CIV', 'FW,MF', 26, 20, 5, '696', Decimal('7.70'), 1, 2, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (21, 'Bernd Leno', 'Arsenal', 'de\xa0GER', 'GK', 29, 4, 4, '360', Decimal('4.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (22, 'Ainsley Maitland-Niles', 'Arsenal', 'eng\xa0ENG', 'MF', 23, 8, 2, '268', Decimal('3.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (23, 'Pablo Marí', 'Arsenal', 'es\xa0ESP', 'DF', 27, 2, 2, '180', Decimal('2.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (24, 'Calum Chambers', 'Arsenal', 'eng\xa0ENG', 'DF', 26, 2, 2, '170', Decimal('1.90'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (25, 'Sead Kolašinac', 'Arsenal', 'ba\xa0BIH', 'DF', 28, 2, 1, '91', Decimal('1.00'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (26, 'Folarin Balogun', 'Arsenal', 'eng\xa0ENG', 'FW', 20, 2, 1, '70', Decimal('0.80'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (27, 'Reiss Nelson', 'Arsenal', 'eng\xa0ENG', 'FW', 21, 1, 0, '20', Decimal('0.20'), 0, 0, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (28, 'Ryan Alebiousu', 'Arsenal', 'eng\xa0ENG', 'DF', 19, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (29, 'Zach Awe', 'Arsenal', 'eng\xa0ENG', 'DF', 17, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (30, 'Miguel Azeez', 'Arsenal', 'eng\xa0ENG', 'MF', 18, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (31, 'Héctor Bellerín', 'Arsenal', 'es\xa0ESP', 'DF,MF', 26, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (32, 'Mika Biereth', 'Arsenal', 'dk\xa0DEN', 'FW', 18, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (33, 'Marcelo Flores', 'Arsenal', 'mx\xa0MEX', 'MF', 17, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (34, 'Omari Hutchinson', 'Arsenal', 'eng\xa0ENG', 'DF', 17, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (35, 'Karl Jakob Hein', 'Arsenal', 'ee\xa0EST', 'GK', 19, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (36, 'Alex Kirk', 'Arsenal', 'eng\xa0ENG', 'DF', 18, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (37, 'Mazeed Ogungbo', 'Arsenal', 'ie\xa0IRL', 'DF', 18, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (38, 'Arthur Okonkwo', 'Arsenal', 'eng\xa0ENG', 'GK', 19, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (39, "Salah Oulad M'Hand", 'Arsenal', 'nl\xa0NED', 'MF', 17, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (40, 'Charlie Patino', 'Arsenal', 'eng\xa0ENG', 'FW', 17, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (41, 'Zak Swanson', 'Arsenal', 'eng\xa0ENG', 'DF', 20, 0, 0, None, None, None, None, 'Arsenal', 'London (Holloway)', 'Emirates Stadium', 60704, 'Mikel Arteta', 'Alexandre Lacazettea', 'Adidas', 'Emirates', 'Visit Rwanda'),
 (42, 'Matty Cash', 'Aston Villa', 'pl\xa0POL', 'DF', 23, 38, 38, '3,377', Decimal('37.50'), 4, 3, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (43, 'Emiliano Martínez', 'Aston Villa', 'ar\xa0ARG', 'GK', 28, 36, 36, '3,240', Decimal('36.00'), 0, 0, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (44, 'Tyrone Mings', 'Aston Villa', 'eng\xa0ENG', 'DF', 28, 36, 35, '3,189', Decimal('35.40'), 1, 3, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (45, 'John McGinn', 'Aston Villa', 'sct\xa0SCO', 'MF', 26, 35, 35, '3,090', Decimal('34.30'), 3, 4, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (46, 'Ollie Watkins', 'Aston Villa', 'eng\xa0ENG', 'FW', 25, 35, 33, '2,952', Decimal('32.80'), 11, 2, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (47, 'Douglas Luiz', 'Aston Villa', 'br\xa0BRA', 'MF', 23, 34, 31, '2,715', Decimal('30.20'), 2, 3, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (48, 'Ezri Konsa', 'Aston Villa', 'eng\xa0ENG', 'DF', 23, 29, 29, '2,477', Decimal('27.50'), 2, 0, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (49, 'Jacob Ramsey', 'Aston Villa', 'eng\xa0ENG', 'MF', 20, 34, 29, '2,467', Decimal('27.40'), 6, 1, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports'),
 (50, 'Emi Buendía', 'Aston Villa', 'ar\xa0ARG', 'FW,MF', 24, 35, 22, '1,899', Decimal('21.10'), 4, 6, 'Aston Villa', 'Birmingham', 'Villa Park', 42682, 'Steven Gerrard', 'Tyrone Mings', 'Kappa', 'Cazoo', 'OB Sports')]