### English Premier League (EPL) Team Data Scraping

Scrap Wikipedia data of english teams which participated in the season of 2021/2022.

In [9]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

URL of WikiPedia page containing 2021/2022 stats:

In [10]:
epl_wiki_url = 'https://en.wikipedia.org/wiki/2021%E2%80%9322_Premier_League#Teams'

Fetch the page and create soup:

In [11]:
response = requests.get(epl_wiki_url)

soup = BeautifulSoup(response.text,'lxml')

Retrieve all table elements:

In [12]:
table_list = soup.find_all('table', attrs={'class':"wikitable sortable"})

In [13]:
df_team_locations = pd.read_html(str(table_list))[0]
display(df_team_locations)

,Team,Location,Stadium,Capacity
0,Arsenal,London (Holloway),Emirates Stadium,60704
1,Aston Villa,Birmingham,Villa Park,42682
2,Brentford,London (Brentford),Brentford Community Stadium,17250
3,Brighton & Hove Albion,Falmer,Falmer Stadium,31800
4,Burnley,Burnley,Turf Moor,21944
5,Chelsea,London (Fulham),Stamford Bridge,40834
6,Crystal Palace,London (Selhurst),Selhurst Park,25486
7,Everton,Liverpool (Walton),Goodison Park,39414
8,Leeds United,Leeds,Elland Road,37792
9,Leicester City,Leicester,King Power Stadium,32312
10,Liverpool,Liverpool (Anfield),Anfield,53394
11,Manchester City,Manchester (Bradford),Etihad Stadium,53400
12,Manchester United,Manchester (Old Trafford),Old Trafford,74140
13,Newcastle United,Newcastle upon Tyne,St James' Park,52305
14,Norwich City,Norwich,Carrow Road,27244
15,Southampton,Southampton,St Mary's Stadium,32384
16,Tottenham Hotspur,London (Tottenham),Tottenham Hotspur Stadium,62850
17,Watford,Watford,Vicarage Road,22200
18,West Ham United,London (Stratford),London Stadium,60000
19,Wolverhampton Wanderers,Wolverhampton,Molineux Stadium,32050

In [14]:
df_team_personnel = pd.read_html(str(table_list))[1]
display(df_team_personnel)

,Team,Manager,Captain,Kit manufacturer,Shirt sponsor (chest),Shirt sponsor (sleeve)
0,Arsenal,Mikel Arteta,Alexandre Lacazettea,Adidas[44],Emirates[45],Visit Rwanda[46]
1,Aston Villa,Steven Gerrard,Tyrone Mings,Kappa[47],Cazoo[48],OB Sports[49]
2,Brentford,Thomas Frank,Pontus Jansson,Umbro,Hollywoodbets[50],Safetyculture[51]
3,Brighton & Hove Albion,Graham Potter,Lewis Dunk,Nike[52],American Express[52],SnickersUK.com[53]
4,Burnley,Mike Jackson Connor King Ben Mee (joint-careta...,Ben Mee,Umbro[54],Spreadex Sports[55],AstroPay[56]
5,Chelsea,Thomas Tuchel,César Azpilicueta,Nike[57],Threec [58],Hyundaic [59]
6,Crystal Palace,Patrick Vieira,Luka Milivojević,Puma[60],W88[61],Facebank[62]
7,Everton,Frank Lampard,Séamus Coleman,Hummel[63],Cazoo[64],None
8,Leeds United,Jesse Marsch,Liam Cooper,Adidas[65],SBOTOP[66],BOXT[67]
9,Leicester City,Brendan Rodgers,Kasper Schmeichel,Adidas[68],FBS[69],Bia Saigon[70]
10,Liverpool,Jürgen Klopp,Jordan Henderson,Nike[71],Standard Chartered[72],Expedia[73]
11,Manchester City,Pep Guardiola,Fernandinho,Puma[74],Etihad Airways[75],Nexen Tire[76]
12,Manchester United,Ralf Rangnick (interim),Harry Maguire,Adidas[77],TeamViewer[78],Kohler[79]
13,Newcastle United,Eddie Howe,Jamaal Lascelles,Castore[80],FUN88[81],Kayak[82]
14,Norwich City,Dean Smith,Grant Hanley,Joma[83],Lotus Cars[84],JD Sports[85]
15,Southampton,Ralph Hasenhüttl,James Ward-Prowse,Hummel[86],Sportsbet.io[87],Virgin Media[88]
16,Tottenham Hotspur,Antonio Conte,Hugo Lloris,Nike[89],AIA[90],Cinch[91]
17,Watford,Roy Hodgson,TBDb[92],Kelme[93],Stake.com[94],Dogecoin[95]
18,West Ham United,David Moyes,Mark Noble,Umbro[96],Betway[97],Scope Markets[98]
19,Wolverhampton Wanderers,Bruno Lage,Conor Coady,Castore[99],ManBetX[100],Bitci.com[101]

Clean column data, by renaming columns and removing reference brackets:

In [15]:
df_team_locations.columns = ['team', 'location', 'stadium', 'capacity']
df_team_personnel.columns = ['team', 'manager', 'captain', 'kit', 'shirt sponsor', 'sleeve sponsor']

#df_team_locations['capacity'] = df_team_locations['capacity'].apply(lambda x: x.split('[')[0] if x.find('[') else x)
df_team_personnel['captain'] = df_team_personnel['captain'].apply(lambda x: x.split('[')[0] if x.find('[') else x)
df_team_personnel['kit'] = df_team_personnel['kit'].apply(lambda x: x.split('[')[0] if x.find('[') else x)
df_team_personnel['shirt sponsor'] = df_team_personnel['shirt sponsor'].apply(lambda x: x.split('[')[0] if x.find('[') else x)
df_team_personnel['sleeve sponsor'] = df_team_personnel['sleeve sponsor'].apply(lambda x: x.split('[')[0] if x.find('[') else x)

In [16]:
df_team_locations.head()

,team,location,stadium,capacity
0,Arsenal,London (Holloway),Emirates Stadium,60704
1,Aston Villa,Birmingham,Villa Park,42682
2,Brentford,London (Brentford),Brentford Community Stadium,17250
3,Brighton & Hove Albion,Falmer,Falmer Stadium,31800
4,Burnley,Burnley,Turf Moor,21944

In [17]:
df_team_personnel.head()

,team,manager,captain,kit,shirt sponsor,sleeve sponsor
0,Arsenal,Mikel Arteta,Alexandre Lacazettea,Adidas,Emirates,Visit Rwanda
1,Aston Villa,Steven Gerrard,Tyrone Mings,Kappa,Cazoo,OB Sports
2,Brentford,Thomas Frank,Pontus Jansson,Umbro,Hollywoodbets,Safetyculture
3,Brighton & Hove Albion,Graham Potter,Lewis Dunk,Nike,American Express,SnickersUK.com
4,Burnley,Mike Jackson Connor King Ben Mee (joint-careta...,Ben Mee,Umbro,Spreadex Sports,AstroPay

In [18]:
epl_teams = pd.merge(df_team_locations, df_team_personnel)
display(epl_teams)

,team,location,stadium,capacity,manager,captain,kit,shirt sponsor,sleeve sponsor
0,Arsenal,London (Holloway),Emirates Stadium,60704,Mikel Arteta,Alexandre Lacazettea,Adidas,Emirates,Visit Rwanda
1,Aston Villa,Birmingham,Villa Park,42682,Steven Gerrard,Tyrone Mings,Kappa,Cazoo,OB Sports
2,Brentford,London (Brentford),Brentford Community Stadium,17250,Thomas Frank,Pontus Jansson,Umbro,Hollywoodbets,Safetyculture
3,Brighton & Hove Albion,Falmer,Falmer Stadium,31800,Graham Potter,Lewis Dunk,Nike,American Express,SnickersUK.com
4,Burnley,Burnley,Turf Moor,21944,Mike Jackson Connor King Ben Mee (joint-careta...,Ben Mee,Umbro,Spreadex Sports,AstroPay
5,Chelsea,London (Fulham),Stamford Bridge,40834,Thomas Tuchel,César Azpilicueta,Nike,Threec,Hyundaic
6,Crystal Palace,London (Selhurst),Selhurst Park,25486,Patrick Vieira,Luka Milivojević,Puma,W88,Facebank
7,Everton,Liverpool (Walton),Goodison Park,39414,Frank Lampard,Séamus Coleman,Hummel,Cazoo,None
8,Leeds United,Leeds,Elland Road,37792,Jesse Marsch,Liam Cooper,Adidas,SBOTOP,BOXT
9,Leicester City,Leicester,King Power Stadium,32312,Brendan Rodgers,Kasper Schmeichel,Adidas,FBS,Bia Saigon
10,Liverpool,Liverpool (Anfield),Anfield,53394,Jürgen Klopp,Jordan Henderson,Nike,Standard Chartered,Expedia
11,Manchester City,Manchester (Bradford),Etihad Stadium,53400,Pep Guardiola,Fernandinho,Puma,Etihad Airways,Nexen Tire
12,Manchester United,Manchester (Old Trafford),Old Trafford,74140,Ralf Rangnick (interim),Harry Maguire,Adidas,TeamViewer,Kohler
13,Newcastle United,Newcastle upon Tyne,St James' Park,52305,Eddie Howe,Jamaal Lascelles,Castore,FUN88,Kayak
14,Norwich City,Norwich,Carrow Road,27244,Dean Smith,Grant Hanley,Joma,Lotus Cars,JD Sports
15,Southampton,Southampton,St Mary's Stadium,32384,Ralph Hasenhüttl,James Ward-Prowse,Hummel,Sportsbet.io,Virgin Media
16,Tottenham Hotspur,London (Tottenham),Tottenham Hotspur Stadium,62850,Antonio Conte,Hugo Lloris,Nike,AIA,Cinch
17,Watford,Watford,Vicarage Road,22200,Roy Hodgson,TBDb,Kelme,Stake.com,Dogecoin
18,West Ham United,London (Stratford),London Stadium,60000,David Moyes,Mark Noble,Umbro,Betway,Scope Markets
19,Wolverhampton Wanderers,Wolverhampton,Molineux Stadium,32050,Bruno Lage,Conor Coady,Castore,ManBetX,Bitci.com

In [19]:
epl_teams.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   team            20 non-null     object
 1   location        20 non-null     object
 2   stadium         20 non-null     object
 3   capacity        20 non-null     int64
 4   manager         20 non-null     object
 5   captain         20 non-null     object
 6   kit             20 non-null     object
 7   shirt sponsor   20 non-null     object
 8   sleeve sponsor  20 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.6+ KB

Save the data in .csv tables:

In [20]:
epl_teams.to_csv('./data/epl_teams.csv', index=False)